netlify.toml
src/pages/HomePage.jsx

backend url fix

---

src/components/Common/SurveyHeader.jsx
src/stories/MainModal.jsx
src/stories/MainModal.stories.js

Style: modal

---

src/components/Common/DetailHeader/DetailHeader.jsx
src/components/Common/SurveyHeader/SurveyHeader.jsx

fix: header back button

---

src/components/Common/TextArea/TextArea.jsx
src/components/NewEstimate/atoms/ChargeInput.jsx
src/components/NewEstimate/modules/DogProfile.jsx
src/components/NewEstimate/modules/SetCharge.jsx
src/components/NewEstimate/modules/SetDesc.jsx
src/components/NewEstimate/templates/DetailStep.jsx
src/components/NewEstimate/templates/EditStep.jsx
src/components/NewEstimate/templates/FirstStep.jsx
src/components/NewRequest/atoms/SelectDogItem.jsx
src/components/NewRequest/atoms/Selector2.jsx
src/components/NewRequest/atoms/SubTitle.jsx
src/components/NewRequest/modules/SelectDog.jsx
src/components/NewRequest/modules/SelectSignificant.jsx
src/components/NewRequest/templates/SecondStep.jsx
src/pages/NewRequest.jsx
src/pages/estimate/EditEstimate.jsx
src/pages/estimate/NewEstimate.jsx
src/routes/AppRoutes.jsx
src/routes/paths.jsx
src/store/usePageStore.js

> #34 
- 견적서 작성 페이지, 견적서 수정 페이지 마크업
- TextArea 컴포넌트 생성
- Selector2, SubTitle 컴포넌트 수정
https://github.com/user-attachments/assets/59b211a9-ba1a-4e2d-affe-d96719045f92

견적서 작성 페이지 마크업

---

src/components/Common/AddButton/AddButton.css
src/components/Common/Button/Button.css
src/components/Common/Button/Button.jsx
src/components/Common/Header/Header.css
src/components/Common/Modal/Modal.jsx
src/components/Features/DogCompareImg.jsx
src/components/NewEstimate/modules/DogProfile.jsx
src/pages/mypage/MyReviews.jsx
src/pages/mypage/MySalonPage.jsx
src/pages/mypage/PaymentHistory.jsx
src/pages/mypage/RequestHistory.jsx
src/pages/mypage/RequestHistoryDetail.jsx
src/routes/AppRoutes.jsx
src/routes/paths.jsx

견적요청내역, 견적요청상세보기 마크업

---

src/components/Common/RadioButton/RadioButton.jsx
src/components/Features/CertificationsForm.jsx
src/components/Features/ProfileSelector.jsx
src/components/Features/ReviewStars.jsx
src/components/Features/ServiceRegionForm.jsx
src/components/NewRequest/atoms/Selector2.jsx
src/pages/mypage/DogProfile.jsx
src/pages/mypage/EditSalonProfile.jsx
src/pages/mypage/EditSocialProfile.jsx
src/pages/mypage/MySalonPage.jsx
src/pages/mypage/MyUserPage.jsx
src/pages/mypage/Mypage.jsx
src/routes/AppRoutes.jsx

> #51 
- 하드코딩 수정
- 미용사 프로필 수정 페이지 컴포넌트 나누기
- 프로필 이미지 수정 컴포넌트
- 반려견 프로필 수정 기능 구현

내정보 페이지 기능 구현

---

src/components/Common/Navbar/Navbar.jsx

fix: navbar redundant code

---

src/api/auth.js
src/routes/AppRoutes.jsx
src/routes/PrivateRoute.jsx

set role as global state

---

src/api/requestUrls.js
src/api/review.js
src/components/Features/ImageSelector.jsx
src/components/Features/ReviewAccordion.jsx
src/components/Features/ReviewStars.jsx
src/pages/NewReview.jsx
src/pages/SalonProfile.jsx
src/pages/mypage/EditReview.jsx
src/pages/mypage/MyReviews.jsx
src/pages/mypage/MySalonPage.jsx
src/routes/AppRoutes.jsx
src/routes/paths.jsx

리뷰 작성, 수정, 삭제, 조회 API 연동

---

package-lock.json
package.json
public/firebase-messaging-sw.js
src/api/notification.js
src/api/requestUrls.js
src/api/review.js
src/components/Common/Header/Header.jsx
src/pages/Home.jsx
src/pages/Notification.jsx
src/pages/SalonProfile.jsx
src/pages/SalonReviews.jsx
src/pages/Survey/Survey.jsx
src/pages/Survey/SurveyGroomer.jsx
src/pages/Survey/SurveyUser.jsx
src/pages/chat/Chat.jsx
src/pages/mypage/MyReviews.jsx
src/pages/mypage/Mypage.jsx
src/routes/AppRoutes.jsx
src/routes/PrivateRoute.jsx
src/routes/paths.jsx
src/store/useRoleStore.js
src/store/useUserStore.js
src/utils/NotificationService.jsx
src/utils/email-template.html
src/utils/generateEmailTemplate.js

> #87 
> 로그인 체크 로그인 상태 변경시에만 실행
> Firebase 설치
> 실시간 알림 조회, 삭제
> 미용사 공개 프로필에서 유저가 보는 리뷰페이지 없어서 만듦
> useRoleStore --> useUserStore

알림기능 API 연동

---

src/api/notification.js
src/api/payment.js
src/api/requestUrls.js
src/pages/mypage/PaymentHistory.jsx
src/utils/NotificationService.jsx

결제내역페이지 api

---

src/pages/Survey/SurveyGroomer.jsx

> 프로필 수정과 추가와 달리 회원가입쪽 서베이에서는 변경시 onChange로 전역변수 변경하기 때문에 toast error 콜이 너무 많음. 일단은 되돌려 놓음.

remove toast error for groomer survey upon register

---

src/api/dogProfile.js
src/api/socialProfile.js
src/pages/mypage/DogProfile.jsx
src/pages/mypage/EditSocialProfile.jsx

dog & social profile bugfixes

---

src/components/Estimate/modules/SetDesc.jsx
src/components/Request/modules/SelectServiceType.jsx
src/components/Request/templates/SecondStep.jsx
src/store/useRequestStore.js

견적 요청, 견석서 작성 버그 수정

---

src/firebase/firebaseMessaging.js
src/routes/PrivateRoute.jsx

fixed continuous post fcmtoken

---

src/pages/mypage/RequestHistory.jsx

견적서 삭제(미용사가) api에 groomerId 추가

---

src/api/estimate.js

견적서 삭제(미용사가) api에 groomerId 추가 2

---

src/pages/mypage/RequestHistory.jsx

견적요청 삭제(미용사가) 삭제하고 리스트 리프레시

---

src/api/coupon.js
src/api/requestUrls.js
src/components/Common/Navbar/Navbar.jsx
src/pages/Coupon.jsx
src/pages/Home.jsx
src/pages/coupon/Coupon.jsx
src/pages/coupon/CouponImage.jsx
src/pages/mypage/MyCoupons.jsx
src/pages/mypage/MyUserPage.jsx
src/pages/mypage/Mypage.jsx
src/routes/AppRoutes.jsx
src/routes/PrivateRoute.jsx
src/routes/paths.jsx
src/store/useUserStore.js

coupon api

---

index.html
src/components/Common/Header/Header.jsx
src/components/Contest/WinnerProfile.jsx
src/components/Features/ReviewAccordion.jsx
src/components/Layout/Loading.jsx
src/components/Request/templates/ThirdStep.jsx
src/components/Survey/UserSteps/Step6.jsx
src/index.css
src/pages/Contest/Contest.jsx
src/pages/Contest/ContestResult.jsx
src/pages/Home.jsx
src/pages/NewRequest.jsx
src/pages/SalonPublicProfile/SalonDetail.jsx
src/pages/SalonPublicProfile/SalonProfile.jsx
src/pages/SalonReviews.jsx
src/pages/Survey/Survey.jsx
src/pages/Survey/SurveyGroomer.jsx
src/pages/coupon/CouponImage.jsx
src/pages/mypage/DogProfile.jsx
src/pages/mypage/EditSocialProfile.jsx
src/pages/mypage/MyReviews.jsx
src/pages/mypage/MySalonPage.jsx
src/pages/mypage/MyUserPage.jsx
src/pages/mypage/PaymentHistory.jsx
src/pages/mypage/RequestHistory.jsx
src/pages/mypage/RequestHistoryDetail.jsx
src/routes/AppRoutes.jsx
src/routes/PrivateRoute.jsx
src/store/useSurveyUserStore.js
src/themes.js

> 폰트 추가
> 나의 리뷰에서 프로필 사진 누르면 미용사 프로필 화면으로 이동
> 회원가입시 반려견 추가 등록 할때 특징이 리셋 안 되어있어서 수정
> 토스트 알림 추가
> 견적요청내역 (미용사 페이지) 없음 문구
> 미용사 프로필 피드백 수정
> 로딩 UI 추가
> 리팩

design & feature fixes

---

src/pages/coupon/Coupon.jsx

remove hardcoded localhost url

---

src/pages/Contest/Contest.jsx

fix:콘테스트 날짜에 맞춰서 수정

---

src/pages/Notification.jsx
src/routes/AppRoutes.jsx

fix navigate from notification to chatroom

---

src/pages/Contest/Contest.jsx

fix:콘테스트 시작일-종료일 로직 수정

---

src/components/Chatting/modules/ChatHeader.jsx
src/components/Chatting/templates/Chatmain.jsx
src/components/Common/DateModal.jsx
src/components/Features/ReviewAccordion.jsx
src/components/Request/atoms/Selector2.jsx
src/pages/Contest/Contest.jsx
src/pages/Home.jsx
src/pages/Notification.jsx
src/pages/SalonReviews.jsx
src/pages/mypage/Mypage.jsx

예약 시간, 로딩, 리뷰 프로필 클릭 수정

---

src/pages/estimate/ViewEstimate.jsx

Fix: date format

---

src/api/coupon.js
src/components/Chatting/modules/ChatNavbar.jsx
src/components/Common/Button/Button.jsx
src/components/Common/Card.jsx
src/components/Common/Carousel.jsx
src/components/Common/Navbar/Navbar.jsx
src/components/Contest/Feed.jsx
src/components/Contest/WinnerProfile.jsx
src/components/Features/ReviewAccordion.jsx
src/pages/Contest/ContestPosts.jsx
src/pages/Home.jsx
src/pages/SalonPublicProfile/SalonProfile.jsx
src/pages/coupon/Coupon.jsx
src/pages/coupon/HomeCouponBanner.jsx
src/pages/coupon/style.css
src/pages/mypage/RequestHistory.jsx
src/themes.js

bugfixes and added countdown to coupon
